# Makefile for the FIH kernel device drivers.
obj-$(CONFIG_FIH_APR) += fih_apr.o
obj-y += fih_camera_dev.o
obj-$(CONFIG_FIH_MFD) += fih_mfd.o
obj-y += fih_rere.o
obj-$(CONFIG_FIH_LCM) += fih_lcm.o
obj-$(CONFIG_FIH_TOUCH) += fih_touch.o
obj-$(CONFIG_FIH_HWCONFIG) += fih_swid.o
obj-$(CONFIG_FIH_HALL_SENSOR) += hallsensor/
